# Simulation / environment defaults
NUM_SERVERS = 8
SERVER_CAPACITY = 100
NUM_KEYS_UNIFORM = 1000
NUM_KEYS_SKEWED = 1000

# Hash ring tuning
NUM_VIRTUAL_NODES = 100
HASH_SPACE_SIZE = 2**32
MAX_RJ_ATTEMPTS = 50

# DLB / training defaults (optional)
DLB_EPOCHS = 1
DLB_TRAINING_SIZE = 1000
DLB_ZIPF_ALPHA = 1.5
